#define DEF_DYNAMICOBJECT_FIRE			1
#define DEF_DYNAMICOBJECT_FISH			2
#define DEF_DYNAMICOBJECT_FISHOBJECT	3
#define DEF_DYNAMICOBJECT_MINERAL1		4
#define DEF_DYNAMICOBJECT_MINERAL2		5
#define DEF_DYNAMICOBJECT_ARESDENFLAG1	6
#define DEF_DYNAMICOBJECT_ELVINEFLAG1	7
#define DEF_DYNAMICOBJECT_ICESTORM		8
#define DEF_DYNAMICOBJECT_SPIKE			9
#define DEF_DYNAMICOBJECT_PCLOUD_BEGIN	10
#define DEF_DYNAMICOBJECT_PCLOUD_LOOP	11
#define DEF_DYNAMICOBJECT_PCLOUD_END	12
#define DEF_DYNAMICOBJECT_FIRE2			13
#define DEF_DYNAMICOBJECT_FIRE3			14 // Widah, for FireBow

// ========== RAGNAROS TELEGRAPHED FIRE ZONES ==========
#define DEF_DYNAMICOBJECT_FIRE_WARNING	15	// Visual warning marker (no damage)
#define DEF_DYNAMICOBJECT_FIRE_INTENSE	16	// Intense fire zone (high damage)

